Switch to cmake
qwexfour/mugratree pull request #1
Opened 2020-05-04 17:42 UTC by Basiliuss

2020-05-04 18:03 UTC, qwexfour requested changes

2020-05-04 18:03 UTC, qwexfour commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.16)
3.16 is too advanced, I believe. 3.0 is definitely enough here.

2020-05-04 18:03 UTC, qwexfour commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
It's better to do with a feature.

2020-05-04 18:03 UTC, qwexfour commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "-lm -Wall -Werror -pedantic-errors -O0")
There's target_link_libraries to link with libraries. Also I don't think we need math library here. So it can be excluded.
-Werror is dangerous to add, because different compilers have different warnings, and some one with new compiler may fail to build the project. And adding -O0 explicitely is not a good idea, let cmake_build_type deside which optimization level to use.

2020-05-04 18:03 UTC, qwexfour commented on CMakeLists.txt
> +set(SOURCES main.cpp forest.cpp)
forest.cpp is not a part of testForest executable, it is part of NLCL library. testForset executable must link with this library.

2020-05-04 18:09 UTC, Basiliuss commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "-lm -Wall -Werror -pedantic-errors -O0")
Just copied from makefile))

2020-05-04 18:11 UTC, Basiliuss commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
why?

2020-05-04 18:54 UTC, qwexfour commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
Because feature can be set on a specific target. And can be populated through INTERFACE, PUBLIC qualifiers.

2020-05-04 19:00 UTC, qwexfour requested changes
please squash it in one commit

2020-05-04 19:00 UTC, qwexfour commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
Something like:
target_compile_features(NLCL PUBLIC cxx_std_17)

2020-05-04 19:00 UTC, qwexfour commented on CMakeLists.txt
> +add_library(forest forest.cpp)
please call the library NLCL

2020-05-04 23:37 UTC, qwexfour requested changes

2020-05-04 23:37 UTC, qwexfour commented on CMakeLists.txt
> +target_compile_options(NLCL PUBLIC -Wall -pedantic-errors)
Those options probably should be private.

2020-05-05 12:04 UTC, qwexfour commented on CMakeLists.txt
> +target_compile_options(NLCL PUBLIC -Wall -pedantic-errors)
```suggestion
target_compile_options(NLCL PRIVATE -Wall -pedantic-errors)
```

2020-05-05 12:16 UTC, merged